export const weeklyData = [
  { name: "Week 1", value: 65 },
  { name: "Week 3", value: 38 },
  { name: "Week 5", value: 18 },
  { name: "Week 7", value: 25 },
  { name: "Week 9", value: 32 },
  { name: "Week 11", value: 25 },
  { name: "Week 13", value: 20 },
  { name: "Week 15", value: 30 },
  { name: "Week 17", value: 42 },
  { name: "Week 19", value: 28 },
  { name: "Week 21", value: 12 },
  { name: "Week 23", value: 28 },
  { name: "Week 25", value: 58 },
  { name: "Week 27", value: 38 },
  { name: "Week 29", value: 15 },
  { name: "Week 31", value: 35 },
  { name: "Week 33", value: 58 },
  { name: "Week 35", value: 55 },
  { name: "Week 37", value: 52 },
  { name: "Week 39", value: 65 },
  { name: "Week 41", value: 92 },
  { name: "Week 43", value: 72 },
  { name: "Week 45", value: 42 },
  { name: "Week 47", value: 55 },
];

export const monthlyData = [
  { name: "January", value: 65 },
  { name: "February", value: 12 },
  { name: "March", value: 26 },
  { name: "April", value: 15 },
  { name: "May", value: 35 },
  { name: "June", value: 5 },
  { name: "July", value: 52 },
  { name: "August", value: 10 },
  { name: "September", value: 52 },
  { name: "October", value: 46 },
  { name: "November", value: 88 },
  { name: "December", value: 36 },
];
